# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '友盟推送' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 友盟推送
pod 'UMessage'
#pod 'JPush' 
pod 'Shimmer'

  target '友盟推送Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '友盟推送UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
